## House Price Prediction Kaggle Competition
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [4]:
train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [6]:
train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [7]:
train.drop('Id', inplace=True, axis=1)
test.drop('Id', inplace=True, axis=1)

In [8]:
train.drop(['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'MasVnrType', 'FireplaceQu'], inplace=True, axis=1)

In [9]:
train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [10]:
train.isnull().sum()[train.isnull().sum() > 0]

LotFrontage     259
MasVnrArea        8
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Electrical        1
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageQual       81
GarageCond       81
dtype: int64

In [11]:
# Fill numeric columns
train['LotFrontage'] = train['LotFrontage'].fillna(train['LotFrontage'].mean())
train['MasVnrArea'] = train['MasVnrArea'].fillna(train['MasVnrArea'].mean())
train['GarageYrBlt'] = train['GarageYrBlt'].fillna(train['GarageYrBlt'].median())

# Safe mode-based fillna function
def safe_mode_fill(df, column, default='None'):
    mode_val = df[column].mode()
    if not mode_val.empty:
        df[column] = df[column].fillna(mode_val.iloc[0])
    else:
        df[column] = df[column].fillna(default)

# Apply safe filling for categorical columns
safe_mode_fill(train, 'BsmtCond')
safe_mode_fill(train, 'BsmtExposure')
safe_mode_fill(train, 'BsmtFinType1')
safe_mode_fill(train, 'BsmtFinType2')
safe_mode_fill(train, 'Electrical')
safe_mode_fill(train, 'GarageType')
safe_mode_fill(train, 'GarageFinish')
safe_mode_fill(train, 'GarageQual')
safe_mode_fill(train, 'GarageCond')
safe_mode_fill(train, 'BsmtQual')  # Already handled earlier, moved for consistency

In [12]:
train.isnull().sum()[train.isnull().sum() > 0]

Series([], dtype: int64)

In [13]:
train.to_csv('train1.csv', index=False)

In [14]:
test.isnull().mean().sort_values(ascending=False).head(10)

PoolQC          0.997944
MiscFeature     0.965045
Alley           0.926662
Fence           0.801234
MasVnrType      0.612748
FireplaceQu     0.500343
LotFrontage     0.155586
GarageYrBlt     0.053461
GarageFinish    0.053461
GarageQual      0.053461
dtype: float64

In [15]:
test.drop(['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'MasVnrType', 'FireplaceQu'], axis=1, inplace=True)

In [16]:
test.isnull().sum()[test.isnull().sum() > 0]

MSZoning          4
LotFrontage     227
Utilities         2
Exterior1st       1
Exterior2nd       1
MasVnrArea       15
BsmtQual         44
BsmtCond         45
BsmtExposure     44
BsmtFinType1     42
BsmtFinSF1        1
BsmtFinType2     42
BsmtFinSF2        1
BsmtUnfSF         1
TotalBsmtSF       1
BsmtFullBath      2
BsmtHalfBath      2
KitchenQual       1
Functional        2
GarageType       76
GarageYrBlt      78
GarageFinish     78
GarageCars        1
GarageArea        1
GarageQual       78
GarageCond       78
SaleType          1
dtype: int64

In [17]:
num_cols_median = [
    'LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 
    'BsmtUnfSF', 'TotalBsmtSF', 'GarageYrBlt', 
    'GarageCars', 'GarageArea', 'BsmtFullBath', 'BsmtHalfBath'
]

for col in num_cols_median:
    test[col] = test[col].fillna(test[col].median())


cat_cols_mode = [
    'MSZoning', 'Utilities', 'Exterior1st', 'Exterior2nd', 'KitchenQual', 
    'Functional', 'SaleType'
]

for col in cat_cols_mode:
    test[col] = test[col].fillna(test[col].mode()[0])


none_fill_cols = [
    'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
    'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'
]

for col in none_fill_cols:
    test[col] = test[col].fillna('None')

In [18]:
test.isnull().sum()[test.isnull().sum() > 0]

Series([], dtype: int64)

In [19]:
test.to_csv('test1.csv', index=False)

It showa empty series. It means all the missing/null values are handled. And now there are no missing value in the dataset.

### Now Let's encode the categorical Features

In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, TargetEncoder
encoder1 = LabelEncoder()
encoder2 = OneHotEncoder()
encoder3 = TargetEncoder()

In [23]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Load data
train = pd.read_csv("train1.csv")
test = pd.read_csv('test1.csv')

# Define categorical columns
categorical_cols = [
    'MSZoning', 'Street', 'LotShape', 'LandContour',
    'Utilities', 'LotConfig', 'LandSlope', 'Condition1',
    'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl',
    'Foundation', 'Heating', 'CentralAir', 'Electrical',
    'GarageType', 'PavedDrive', 'SaleType', 'SaleCondition'
]

# Drop rows with missing target (if applicable)
train = train.dropna(subset=["SalePrice"]) if "SalePrice" in train.columns else train
test = test.dropna(subset=["SalePrice"]) if "SalePrice" in test.columns else train

# Numerical columns (excluding target and categorical ones)
numerical_cols = [col for col in train.columns if col not in categorical_cols + ["SalePrice"]]

numerical_cols2 = [col for col in test.columns if col not in categorical_cols + ["SalePrice"]]

# Preprocessing pipeline for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

# Column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='passthrough'
)

# Fit and transform
encoded_array = preprocessor.fit_transform(train)
encoded_array = preprocessor.fit_transform(test)

# Extract new column names
ohe = preprocessor.named_transformers_['cat']['onehot']
encoded_cat_cols = ohe.get_feature_names_out(categorical_cols)
final_column_names = list(encoded_cat_cols) + numerical_cols + ["SalePrice"]
final_column_names2 = list(encoded_cat_cols) + numerical_cols2 + ["SalePrice"]

# Convert to DataFrame
df_encoded = pd.DataFrame(encoded_array, columns=final_column_names)
df_encoded2 = pd.DataFrame(encoded_array, columns=final_column_names2)

# Ensure correct data types (optional, but safe)
df_encoded = df_encoded.convert_dtypes()
df_encoded2 = df_encoded2.convert_dtypes()

# Save if needed
df_encoded.to_csv("encoded_train_data.csv", index=False)
df_encoded2.to_csv("encoded_test_data.csv", index=False)

In [26]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# Load the data
train = pd.read_csv("encoded_train_data.csv")
test = pd.read_csv("encoded_test_data.csv")

# Target separation (if you're training a model)
y = train["SalePrice"]
train = train.drop("SalePrice", axis=1)

# Columns to apply label encoding
label_encode_cols = [
    "MSSubClass", "ExterQual", "ExterCond", "BsmtQual", "BsmtCond",
    "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "HeatingQC",
    "KitchenQual", "Functional", "GarageFinish", "GarageQual",
    "GarageCond"
]

# Define the label encoder pipeline
label_encoder = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value="NA")),
    ("encoder", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))
])

# Apply only to the selected columns
preprocessor = ColumnTransformer(
    transformers=[
        ("label_enc", label_encoder, label_encode_cols)
    ],
    remainder="passthrough"  # Keep all other columns unchanged
)

# Fit on train, transform both train and test
train_encoded = preprocessor.fit_transform(train)
test_encoded = preprocessor.transform(test)

# Build column names: label encoded + rest
rest_cols = [col for col in train.columns if col not in label_encode_cols]
final_columns = label_encode_cols + rest_cols

# Convert to DataFrames
X_train = pd.DataFrame(train_encoded, columns=final_columns)
X_test = pd.DataFrame(test_encoded, columns=final_columns)

# Add back target to training set
X_train["SalePrice"] = y.values

# Save if needed
X_train.to_csv("train_label_encoded.csv", index=False)
X_test.to_csv("test_label_encoded.csv", index=False)

In [54]:
import pandas as pd

# Load datasets
train = pd.read_csv("train_label_encoded.csv")
test = pd.read_csv("test_label_encoded.csv")

# Drop rows with missing SalePrice
train = train.dropna(subset=["SalePrice"])

# Save target and drop from train
y = train["SalePrice"]
X = train.drop("SalePrice", axis=1)

# Step 1: Compute mean SalePrice per Neighborhood in train
neighborhood_target_mean = train.groupby("Neighborhood")["SalePrice"].mean()

# Step 2: Map this mean to both train and test sets
X["Neighborhood_TE"] = X["Neighborhood"].map(neighborhood_target_mean)
test["Neighborhood_TE"] = test["Neighborhood"].map(neighborhood_target_mean)

# Step 3: If some neighborhoods in test are not in train, fill with global mean
global_mean = y.mean()
test["Neighborhood_TE"] = test["Neighborhood_TE"].fillna(global_mean)

# Optional: Drop original column if no longer needed
X = X.drop("Neighborhood", axis=1)
test = test.drop("Neighborhood", axis=1)

# Optional: Add target back to train
X["SalePrice"] = y

# Save encoded datasets
X.to_csv("train_target_encoded.csv", index=False)
test.to_csv("test_target_encoded.csv", index=False)

In [44]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [40]:
%pip install xgboost

Collecting xgboost
  Using cached xgboost-3.0.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in e:\house price prediction\venv3\lib\site-packages (from xgboost) (1.24.0)
Requirement already satisfied: scipy in e:\house price prediction\venv3\lib\site-packages (from xgboost) (1.15.2)
Using cached xgboost-3.0.2-py3-none-win_amd64.whl (150.0 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.0.2
Note: you may need to restart the kernel to use updated packages.

In [68]:
from sklearn.model_selection import train_test_split
train_df = pd.read_csv('train_target_encoded.csv')
test_df = pd.read_csv('test_target_encoded.csv')

X = train_df.drop(['SalePrice', 'Exterior1st', 'Exterior2nd'], axis=1)
y = train_df['SalePrice']

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = root_mean_squared_error(true, predicted)
    r2_square = r2_score(true, predicted)
    return mae, mse, rmse, r2_square

In [74]:
# model training
models = {
    'Linear Regression' : LinearRegression(),
    'Logistic Regression' : LogisticRegression(),
    'K Neighbors Regressor' : KNeighborsRegressor(),
    'Decision Tree Regressor' : DecisionTreeRegressor(),
    'Random Forest' : RandomForestRegressor(),
    'AdaBoost Regressor' : AdaBoostRegressor(),
    'Gradient Boosting Regressor' : GradientBoostingRegressor(),
    'XGBoost Regressor' : XGBRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_mse, model_train_rmse, model_train_r2score = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_rmse, model_test_r2score = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2score))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2score))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 22841.4052
- Mean Absolute Error: 15419.4805
- R2 Score: 0.9125
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 49471.4777
- Mean Absolute Error: 21001.5635
- R2 Score: 0.6809
===================================

E:\House Price Prediction\venv3\lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Model performance for Training set
- Root Mean Squared Error: 67250.2837
- Mean Absolute Error: 45344.6190
- R2 Score: 0.2418
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 74658.5551
- Mean Absolute Error: 47596.4007
- R2 Score: 0.2733
===================================


K Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 34139.5648
- Mean Absolute Error: 21985.6271
- R2 Score: 0.8046
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 43753.2520
- Mean Absolute Error: 27147.9527
- R2 Score: 0.7504
===================================


Decision Tree Regressor
Model performance for Training set
- Root Mean Squared Error: 0.0000
- Mean Absolute Error: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 40174.7539
- Mean Absolute Error: 25091.7808
- R2 Score: 0.7896
===================================


Random Forest
Model performance for Training set
- Root Mean Squared Error: 10819.7756
- Mean Absolute Error: 6460.4165
- R2 Score: 0.9804
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 28549.9260
- Mean Absolute Error: 16994.5574
- R2 Score: 0.8937
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 26296.4811
- Mean Absolute Error: 20696.3163
- R2 Score: 0.8841
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 32662.3150
- Mean Absolute Error: 23101.1267
- R2 Score: 0.8609
===================================


Gradient Boosting Regressor
Model performance for Training set
- Root Mean Squared Error: 13554.6831
- Mean Absolute Error: 9921.2651
- R2 Score: 0.9692
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 24723.1970
- Mean Absolute Error: 16094.9161
- R2 Score: 0.9203
===================================


XGBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 1271.2797
- Mean Absolute Error: 890.0168
- R2 Score: 0.9997
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 26410.5508
- Mean Absolute Error: 16106.6494
- R2 Score: 0.9091
===================================

In [76]:
test_data = pd.read_csv('test_target_encoded.csv')

In [78]:
test_data.drop(['Exterior1st', 'Exterior2nd'], axis=1, inplace=True)

In [80]:
y_pred = model.predict(test_data)

In [86]:
y_pred

array([205333.5 , 181612.52, 222635.55, ..., 265820.1 , 142037.08,
       148109.22], dtype=float32)

In [110]:
prediction = pd.DataFrame(y_pred, columns=['SalePrice'])
prediction.index = range(1461, 1461 + len(prediction))

# Save to CSV
prediction.to_csv("solution.csv", index_label="Id")

In [112]:
prediction

          SalePrice
1461  205333.500000
1462  181612.515625
1463  222635.546875
1464  141216.515625
1465  251468.281250
...             ...
2916  174816.109375
2917  209241.812500
2918  265820.093750
2919  142037.078125
2920  148109.218750

[1460 rows x 1 columns]

In [ ]:
## hyperparameter tunning

rf_params = {
    'n_estimators' : [100, 200, 500],
    'criterion' : ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
    'max_depth' : [3, 5, None],
    'min_samples_split' : [2, 5, 8],
}

grad_params = {
    'loss' : ['squared_error', 'absolute_error', 'huber', 'quantile'],
    'learning_rate' : [0.1, 0.001, 0.01],
    'n_estimators' : [100, 200, 500],
    'criterion' : ['friedman_mse', 'squared_error'],
    'min_samples_split' : [2, 3, 5, None]
}

xgb_params = {